import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { createContext, useState } from "react";
import PortfolioSlider from "../components/PortfolioSlider";
import ReactSwitch from "react-switch";
import Form from "../components/Form";
import Link from 'next/link'
export const ThemeContext = createContext(null);
export default function Home() {
const [theme, setTheme] = useState("dark");
const [changeBcg, setChangeBcg] = useState(false);

  const toggleTheme = () => {
    setTheme((curr) => (curr === "light" ? "dark" : "light"));
  };
  const changeNavBcg=()=>{
    if(window.scrollY >= 100){
    setChangeBcg(true)
    }else{
      setChangeBcg(false)
    }
  }
  if (typeof window !== "undefined") { 
    window.addEventListener('scroll', changeNavBcg);
   }
 
  const currentYear= new Date().getFullYear();

  return (
    <>
      <Head>
        <title>Emamuzo Omokiti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/o.png" />
      </Head>
    
      <ThemeContext.Provider value={{ theme, toggleTheme }}>
      <main> 
        <div className="contain" id={theme}>
          <div className="col-md-12">
            <div className="row">
              <nav className={`navbar navbar-expand-lg ${changeBcg ? 'active':""}`}>
                <div className="container-fluid">
                  <Link href="/">
                    <a className="navbar-brand">Emamuzo</a>
                  </Link>
                  <button
                    className="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <span className="navbar-toggler-icon"></span>
                  </button>
                  <div
                    className="collapse navbar-collapse"
                    id="navbarSupportedContent"
                  >
                    <ul className="navbar-nav ms-auto mb-2 mb-lg-0">
                      <li className="nav-item">
                        <a className="nav-link" href="#aboutme">
                          About
                        </a>
                      </li>
                      <li className="nav-item">
                        <a className="nav-link" href="#">
                        Resumé
                        </a>
                      </li>
                      <li className="nav-item">
                        <a className="nav-link" href="#myportfolio">
                          Projects
                        </a>
                      </li>
                      <li className="nav-item">
                        <a
                          className="nav-link"
                          href="https://emaomokiti.hashnode.dev/"
                        >
                          Blog
                        </a>
                      </li>
                      <li className="nav-item">
                        <a className="nav-link" href="#contactform">
                          Contact
                        </a>
                      </li>
                      <li className="nav-item navz">
                        <ReactSwitch
                          onChange={toggleTheme}
                          checked={theme === "dark"}
                          onColor="#FFFFFF"
                          onHandleColor="#FFFFFF"
                          uncheckedIcon={false}
                          checkedIcon={false}
                          boxShadow="0px 1px 5px rgba(0, 0, 0, 0.6)"
                          activeBoxShadow="0px 0px 1px 10px rgba(0, 0, 0, 0.2)"
                          className="react-switch"
                          id="material-switch"
                        />
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
            </div>
          </div>
          <section className="space">
            <div className="headercontain">
              <div className="info">
                <h2 className="header ">/EmamuzoːOmokiti/</h2>
                <p className="intro">
                Frontend Developer
                  
                </p>
                {theme ==="dark" ? <img src="/line.svg" alt="line"/> : theme === "light"?<img src="/Lines.svg" alt="line"/>:null}
                 {/* <img src="/line.svg" alt="line"className="line"/> */}
                {/* <img src="/line 793.svg" alt="line"className="line"/> */}
                <p className="introduction">A creative developer who enjoys creating beautiful user-interface
                 using the right technologies.
                 </p>
                <a className="myworks_btn" href="#myportfolio">
                  MY WORKS
                </a>
              </div>
              <div>
              
                <img src="/profile_pic.png" className="my_image" />
            
              </div>
            </div>
          </section>
          {/* about me section */}
          <section className="aboutme" id="aboutme" >
        
            <div className="aboutme_box" data-aos="fade-right">
              <div>
                {/* <Animation/> */}
                <h2 className="aboutme_header">About Me</h2>
                <p className="aboutme_info">I am a creative Front-end developer based in Lagos, Nigeria.
                  I got interested in tech after randomly attending a tech workshop for ladies during National Youth Service Corp Year.
                  I practiced on free code camp for a while then attended the Stutern Garduate Acceleratoe programme. 
                   this programme I fully transitioned from being an Agroeconomist to tech. 
                  So far, I have worked in financial technology and human resource technology.</p>
              </div>
              <div>
               
            <div className="technologies_box">
              <h5 className="technologies_header">Technologies</h5>
              <span className="tech">Html 5</span>
              <span className="tech">CSS3</span>
              <span className="tech"> Sass</span>
              <span className="tech">Javascript</span>
              <span className="tech">React</span>
              
            </div>
               
              </div>
              <div className="ch_box">
                <div className="hobbies">
                  <h5 className="technologies_header">Hobbies</h5>
                  <span className="tech"> Novels</span>
                  <span className="tech">Blogging</span>
                  <span className="tech">Music</span>
                  <span className="tech">Movies</span>
                   </div>
                <div className="community">
                  <h5 className="technologies_header">Community</h5>
                  <span className="tech">Stutern</span>
                  <span className="tech">She Code&apos;s Africa</span>
                </div>
              </div>
            </div>
          </section>
          {/* portfolio */}
          <section id="myportfolio" className="portfolio">
          <h2 className="subheader">My Works</h2>
            < PortfolioSlider/>
          </section>
          {/* contact */}
         <section id="contactform" className="space">
           <div className="contact_me" data-aos="fade-right">
            <div className="infoemail">
              <p className="myemail">eomokiti@yahoo.com</p>
              <h3 className="contactme">Contact Me</h3>
              {theme ==="dark" ? <img src="/line.svg" alt="line"/> : theme === "light"?<img src="/Lines.svg" alt="line"/>:null}
            
              <p className="email_content">I would like to hear from you, if you have any questions about my work or my journey, colloborate with me or just a simple hello.</p>
            </div>
            <div>
            <Form/>
            </div>
          </div>
             </section>
         <footer className="footer space">
          <div className="footer_container">
            <div className="footer_content">
            <p>Emamuzo Omokiti</p>
            <a href="#aboutme" className="footernav"><span className="small_nav">About</span> </a> <a href="#" className="footernav"><span className="small_nav">Resumé</span></a>
            <a href="#myportfolio" className="footernav"> <span className="small_nav">Projects</span> </a> <a href="https://emaomokiti.hashnode.dev/" className="footernav"><span className="small_nav">Blog</span> </a> <a href="#contactform" className="footernav"><span>Contact</span></a>
            </div>
            <div className="footer_socials">
              <p>Find Me</p>
             <a href="https://www.instagram.com/musmus_omokiti"><img src="/fi_instagram.svg" alt="instagram" className="small_nav"/> </a>
             <a href="https://twitter.com/EmamuzoOmokiti"> <img src="/fi_twitter.svg" alt="twitter" className="small_nav"/></a>
              <a href="https://www.linkedin.com/in/emamuzoomokiti"><img src="/fi_linkedin.svg" alt="linkedin" className="small_nav"/></a>
              <a href="https://www.yahoo.com/momokiti@yahoo.com"><img src="/fi_mail.svg" alt="mail" className="small_nav"/></a>
            </div>
          </div>
          <p className="myname">© &nbsp;{currentYear} &nbsp;Emamuzo Omokiti</p>
         </footer>
        </div>
     
        </main>
       
      </ThemeContext.Provider>
     
     
    
    </>
  );
}
